# -*- coding: utf-8 -*-
"""
REL8HF EMV Emulator Lab -- protocol-aware captured transaction replay.

Laboratory scope
----------------
This program is a deterministic local test peer for the REL8HF relay. It does
not connect to an issuer/acquirer and it does not generate production payment
cryptographic values. The ARQC/AC fixtures used after the first GENERATE AC are
synthetic/captured lab values only.

The emulator:
  1. Registers as relay role EMULATOR.
  2. Waits for REGISTER ACK.
  3. Starts SESSION_BEGIN and waits for SESSION_ACK/READY.
  4. Replays the exact eight CAPDUs from the known-good transaction.
  5. Records detailed CAPDU/RAPDU checkpoints for comparison with a real POS.
  6. With --continue-arqc, continues the lab-only post-ARQC path using the
     same synthetic EXT AUTHENTICATE and second-GAC fixtures used by emv_lab1.

Wire format
-----------
Every UDP packet is built through constants.build_frame():
    Length(4) + SID(1) + Epoch(4) + Seq(2) + Payload(N)

APDU payloads are raw. The outer Seq is the CAPDU/RAPDU correlation value.
The optional EXCHANGE_MAGIC wrapper is intentionally not used.
"""

from __future__ import annotations

import sys
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import argparse
import json
import socket
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import constants
import parser as emv_parser
import protocol
import tlv


# ---------------------------------------------------------------------------
# Exact CAPDUs copied from the supplied known-good transaction log.
# ---------------------------------------------------------------------------

CAPDUS: Tuple[bytes, ...] = (
    # 1. SELECT PPSE
    bytes.fromhex("00A404000E325041592E5359532E444446303100"),

    # 2. SELECT Mastercard AID
    bytes.fromhex("00A4040007A000000004101000"),

    # 3. GET PROCESSING OPTIONS (PDOL supplied)
    bytes.fromhex("80A800000A8308000000000000000000"),

    # 4. READ RECORD SFI=2, record=1
    bytes.fromhex("00B2011400"),

    # 5. READ RECORD SFI=4, record=1
    bytes.fromhex("00B2012400"),

    # 6. READ RECORD SFI=4, record=2
    bytes.fromhex("00B2022400"),

    # 7. READ RECORD SFI=4, record=3
    bytes.fromhex("00B2032400"),

    # 8. FIRST GENERATE AC (ARQC request)
    bytes.fromhex(
        "80AE80004200000000100000000000"
        "000009780000000000097826081700"
        "B1525BA12200000000000000000000"
        "1F0302084018000000000000000000"
        "000000000000000000000000"
    ),
)

NAMES = (
    "SELECT PPSE",
    "SELECT AID",
    "GET PROCESSING OPTIONS",
    "READ RECORD SFI=2/1",
    "READ RECORD SFI=4/1",
    "READ RECORD SFI=4/2",
    "READ RECORD SFI=4/3",
    "GENERATE AC",
)

# Lab-only continuation fixtures already used by emv_lab1.py.
EXT_AUTH_APDU = bytes.fromhex("008200000A11223344556677883030")
GAC2_APDU = bytes.fromhex("80AE400000")
SYNTHETIC_EXT_AUTH_RAPDU = constants.SW_9000
SYNTHETIC_GAC2_RAPDU = (
    # Same deterministic TC response generated by the lab card profile:
    # 77 [9F27=40, 9F36=0012, 9F26=1122334455667788, 9F10=06010A030000] 9000
    bytes.fromhex(
        "77189F2701409F360200129F260811223344556677889F100506010A0300009000"
    )
)


@dataclass
class TraceEntry:
    step: int
    phase: str
    direction: str
    name: str
    seq: Optional[int]
    apdu_hex: str
    status: str
    tlv_tags: List[str]
    detail: str
    reference: str


def hx(data: bytes) -> str:
    return bytes(data).hex().upper()


def sw(data: bytes) -> str:
    return hx(data[-2:]) if len(data) >= 2 else ""


def build_frame(sid: int, payload: bytes, *, epoch: int, seq: int) -> bytes:
    return constants.build_frame(
        sid,
        bytes(payload),
        seq=seq & 0xFFFF,
        epoch=epoch,
    )


def _tag_name(tag: Any) -> str:
    if isinstance(tag, int):
        return f"0x{tag:X}"
    return str(tag)


def response_tlv_tags(data: bytes) -> Tuple[List[str], List[str]]:
    """Return top-level TLV tags and parser notes without changing payload."""
    if len(data) < 3:
        return [], []

    body = data[:-2] if len(data) >= 2 else data
    if not body:
        return [], []

    try:
        nodes, errors = emv_parser.parse_ber_tlv(body)
        tags = [_tag_name(node.tag) for node in nodes]
        notes = [str(err) for err in errors]
        return tags, notes
    except Exception as exc:
        return [], [f"TLV parse error: {type(exc).__name__}: {exc}"]


def find_tag(data: bytes, tag: int) -> Optional[bytes]:
    """Best-effort lab diagnostic using the project's TLV helpers."""
    body = data[:-2] if len(data) >= 2 else data
    if not body:
        return None
    try:
        return tlv.find_tlv(body, tag)
    except Exception:
        return None


def decode_rapdu_checkpoint(data: bytes) -> Dict[str, Any]:
    tags, errors = response_tlv_tags(data)
    out: Dict[str, Any] = {
        "sw": sw(data),
        "tlv_tags": tags,
    }
    if errors:
        out["tlv_errors"] = errors

    for tag, label in (
        (0x9F27, "CID_9F27"),
        (0x9F36, "ATC_9F36"),
        (0x9F26, "AC_9F26"),
        (0x9F10, "IAD_9F10"),
        (0x91, "ISSUER_AUTH_91"),
    ):
        value = find_tag(data, tag)
        if value is not None:
            out[label] = hx(value)

    return out


class EmuLab:
    def __init__(
        self,
        relay_host: str,
        relay_port: int,
        *,
        session_id: Optional[str] = None,
        client_id: Optional[str] = None,
        timeout: float = 5.0,
        continue_arqc: bool = False,
        export_path: Optional[Path] = None,
        cdcvm: bool = False,
    ) -> None:
        self.relay_addr = (relay_host, int(relay_port))
        self.timeout = float(timeout)
        self.continue_arqc = bool(continue_arqc)
        self.export_path = Path(export_path) if export_path else None
        self.cdcvm = bool(cdcvm)

        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.bind(("0.0.0.0", 0))
        self.sock.settimeout(0.20)

        self.epoch = 0
        self.protocol_state = "INIT"
        self.ctrl_messages: List[str] = []
        self.session_id = (
            session_id if session_id is not None else str(int(time.time()) % 10000)
        )
        self.client_id = client_id or f"REL8-LAB-EMU-{self.session_id}"
        self.trace: List[TraceEntry] = []
        self._step = 0
        self._seq = 0

    @property
    def local_addr(self) -> Tuple[str, int]:
        return self.sock.getsockname()

    def close(self) -> None:
        try:
            self.sock.close()
        except OSError:
            pass

    def _add_trace(
        self,
        *,
        phase: str,
        direction: str,
        name: str,
        seq: Optional[int],
        apdu: bytes,
        detail: str,
        reference: str = "",
    ) -> None:
        self._step += 1
        self.trace.append(
            TraceEntry(
                step=self._step,
                phase=phase,
                direction=direction,
                name=name,
                seq=seq,
                apdu_hex=hx(apdu),
                status=sw(apdu),
                tlv_tags=response_tlv_tags(apdu)[0] if direction == "RAPDU" else [],
                detail=detail,
                reference=reference,
            )
        )

    # ------------------------------------------------------------------
    # Registration/session control plane
    # ------------------------------------------------------------------

    def send_register(self) -> None:
        self.protocol_state = "REGISTERING"
        payload = (
            f"EMULATOR V{constants.PROTOCOL_VERSION} ID={self.client_id}"
        ).encode("utf-8")
        frame = build_frame(
            constants.SID_REGISTER,
            payload,
            epoch=0,
            seq=0,
        )
        self.sock.sendto(frame, self.relay_addr)
        print(
            f"REGISTER → {self.relay_addr[0]}:{self.relay_addr[1]} "
            f"id={self.client_id}"
        )

    def wait_for_register_ack(self) -> bool:
        deadline = time.monotonic() + self.timeout
        while time.monotonic() < deadline:
            try:
                data, _addr = self.sock.recvfrom(65535)
            except socket.timeout:
                continue

            parsed = constants.parse_frame(data)
            if parsed is None:
                continue

            sid, epoch, _seq, payload = parsed
            if sid == constants.SID_ACK:
                text = payload.decode("utf-8", errors="replace").strip()
                if text.upper() == "REGISTER":
                    self.epoch = epoch
                    self.protocol_state = "REGISTERED"
                    print(f"REGISTER ACK ← epoch={epoch}")
                    return True
            elif sid == constants.SID_CTRL:
                text = payload.decode("utf-8", errors="replace").strip()
                self.ctrl_messages.append(text)
                print(f"CTRL ← {text}")
                if text.upper().startswith("ERR "):
                    self.protocol_state = "ERROR"
                    return False
        return False

    def send_ctrl(self, text: str) -> None:
        command = text.strip().upper()
        if command.startswith("SESSION_BEGIN"):
            self.protocol_state = "SESSION_STARTING"
        frame = build_frame(
            constants.SID_CTRL,
            text.encode("utf-8"),
            epoch=self.epoch,
            seq=0,
        )
        self.sock.sendto(frame, self.relay_addr)
        print(f"CTRL → {text}")

    def wait_for_session_ack(self) -> bool:
        deadline = time.monotonic() + self.timeout
        while time.monotonic() < deadline:
            try:
                data, _addr = self.sock.recvfrom(65535)
            except socket.timeout:
                continue

            parsed = constants.parse_frame(data)
            if parsed is None:
                continue

            sid, epoch, _seq, payload = parsed
            self.epoch = epoch

            if sid == constants.SID_CTRL:
                text = payload.decode("utf-8", errors="replace").strip()
                self.ctrl_messages.append(text)
                print(f"CTRL ← {text}")
                command = text.upper()
                if command.startswith("ERR "):
                    self.protocol_state = "ERROR"
                    return False
                if command.startswith("SESSION_ACK") or command.startswith(
                    "SESSION_READY"
                ):
                    self.protocol_state = "SESSION_READY"
                    return True

            elif sid == constants.SID_ACK:
                text = payload.decode("utf-8", errors="replace").strip()
                print(f"ACK ← {text}")
                if text.upper() in {"SESSION_BEGIN", "SESSION", "READY"}:
                    self.protocol_state = "SESSION_READY"
                    return True

        self.protocol_state = "ERROR"
        return False

    # ------------------------------------------------------------------
    # APDU transport
    # ------------------------------------------------------------------

    def send_apdu(self, apdu: bytes, *, seq: int, phase: str, name: str) -> None:
        if self.protocol_state != "SESSION_READY":
            raise RuntimeError(
                f"cannot send APDU seq={seq}: state={self.protocol_state}"
            )

        self.protocol_state = "EXCHANGING"
        frame = build_frame(
            constants.SID_CAPDU,
            apdu,
            epoch=self.epoch,
            seq=seq,
        )
        self.sock.sendto(frame, self.relay_addr)

        self._add_trace(
            phase=phase,
            direction="CAPDU",
            name=name,
            seq=seq,
            apdu=apdu,
            detail=f"len={len(apdu)} epoch={self.epoch}",
        )

        print(
            f"CAPDU #{seq} → {name:24s} "
            f"len={len(apdu):2d} {hx(apdu)}"
        )

    def wait_for_rapdu(
        self,
        *,
        wanted_seq: int,
        phase: str,
        name: str,
        reference_response: Optional[bytes] = None,
    ) -> Optional[bytes]:
        deadline = time.monotonic() + self.timeout

        while time.monotonic() < deadline:
            try:
                data, _addr = self.sock.recvfrom(65535)
            except socket.timeout:
                continue

            parsed = constants.parse_frame(data)
            if parsed is None:
                continue

            sid, epoch, seq, payload = parsed
            self.epoch = epoch

            if sid == constants.SID_CTRL:
                text = payload.decode("utf-8", errors="replace").strip()
                self.ctrl_messages.append(text)
                print(f"CTRL ← {text}")
                if text.upper().startswith("ERR "):
                    self.protocol_state = "ERROR"
                    return None
                continue

            if sid != constants.SID_RAPDU:
                continue

            if seq != (wanted_seq & 0xFFFF):
                print(
                    f"IGNORING RAPDU seq={seq}; waiting for seq={wanted_seq}"
                )
                continue

            checkpoint = decode_rapdu_checkpoint(payload)
            reference = ""
            if reference_response is not None:
                if payload == reference_response:
                    reference = "EXACT_MATCH_KNOWN_GOOD"
                else:
                    reference = "DIFFERS_FROM_KNOWN_GOOD"

            self._step += 1
            self.trace.append(
                TraceEntry(
                    step=self._step,
                    phase=phase,
                    direction="RAPDU",
                    name=name,
                    seq=wanted_seq,
                    apdu_hex=hx(payload),
                    status=sw(payload),
                    tlv_tags=checkpoint.get("tlv_tags", []),
                    detail=json.dumps(checkpoint, sort_keys=True),
                    reference=reference,
                )
            )

            print(
                f"RAPDU #{wanted_seq} ← "
                f"len={len(payload):2d} SW={sw(payload)} "
                f"{hx(payload)}"
            )
            self._print_checkpoint(wanted_seq, checkpoint, reference)
            self.protocol_state = "SESSION_READY"
            return payload

        return None

    # ------------------------------------------------------------------
    # Diagnostic reporting
    # ------------------------------------------------------------------

    @staticmethod
    def _print_checkpoint(
        seq: int,
        checkpoint: Dict[str, Any],
        reference: str,
    ) -> None:
        print(f"  [CHECKPOINT #{seq}] SW={checkpoint.get('sw', '')}")
        if checkpoint.get("tlv_tags"):
            print(
                "  [TLV] "
                + ", ".join(checkpoint["tlv_tags"])
            )
        for label in ("CID_9F27", "ATC_9F36", "AC_9F26", "IAD_9F10", "ISSUER_AUTH_91"):
            if label in checkpoint:
                print(f"  [TLV] {label}={checkpoint[label]}")
        if reference:
            print(f"  [REFERENCE] {reference}")

    def print_trace(self) -> None:
        print()
        print("SIDE-BY-SIDE LAB CHECKPOINT TRACE")
        print("=" * 110)
        print(
            f"{'#':>2} {'PHASE':18s} {'DIR':7s} {'NAME':24s} "
            f"{'SEQ':>3} {'SW':>4} {'REFERENCE':28s}"
        )
        print("-" * 110)
        for item in self.trace:
            print(
                f"{item.step:2d} {item.phase:18.18s} {item.direction:7.7s} "
                f"{item.name:24.24s} "
                f"{str(item.seq) if item.seq is not None else '-':>3} "
                f"{item.status or '-':>4} "
                f"{item.reference or '-':28.28s}"
            )

        print("=" * 110)
        print("Use this trace as the lab-side baseline when comparing the real POS.")
        print("A real-POS stall at AID SELECT means the divergence occurs before")
        print("GPO; a stall after first GAC points at ARQC/issuer-auth handling.")

    # ------------------------------------------------------------------
    # Transaction
    # ------------------------------------------------------------------

    def run(self) -> int:
        print("REL8HF EMV EMULATOR LAB")
        print("=" * 60)
        print(f"relay : {self.relay_addr[0]}:{self.relay_addr[1]}")
        print(f"local : {self.local_addr[0]}:{self.local_addr[1]}")
        print(f"session: {self.session_id}")
        print(f"client : {self.client_id}")
        print(f"CAPDUs: {len(CAPDUS)}")
        print(f"mode  : captured replay{' + synthetic ARQC continuation' if self.continue_arqc else ''}{' + CDCVM BIOMETRIC' if self.cdcvm else ''}")
        print()

        # Exact RAPDUs corresponding to the eight CAPDUs above.
        # The PPSE uses the structurally valid 84-byte lab variant.
        reference_responses = (
            # 1. SELECT PPSE
            bytes.fromhex(
                "6F50840E325041592E5359532E4444463031A53EBF0C3B611E4F07A000000004101050104465626974204D61737465726361726487010161194F07A0"
                "000000031010500B56697361204372656469748701019000"
            ),

            # 2. SELECT Mastercard AID
            bytes.fromhex(
                "6F658407A0000000041010A55A50104465626974204D6173746572636172648701019F38039F5C085F2D02656E9F1101019F12104465626974204D61"
                "7374657263617264BF0C209F4D020B0A9F6E07082600003030009F5D030100069F0A0800010501000000009000"
            ),

            # 3. GET PROCESSING OPTIONS
            bytes.fromhex(
                "770E82020980940810010101200103009000"
            ),

            # 4. READ RECORD SFI=2, record=1
            bytes.fromhex(
                "7081BE9F420208265F25032512015F24033012315A0853552220917791575F3401009F0702FFC09F080200028C279F02069F03069F1A0295055F2A02"
                "9A039C019F37049F35019F45029F4C089F34039F21039F7C148D12910A8A0295059F37049F4C089F02069F03068E10000000000000000000001F031E"
                "0300009F51039F37049F5B0CDF6008DF6108DF6201DF63A09F0D0500000000009F0E0500000000009F0F0500000000005F28020826570E5355222091"
                "779157D301222106109F4A01829000"
            ),

            # 5. READ RECORD SFI=4, record=1
            bytes.fromhex(
                "7081C59F4681B02945DCF8866BFE7D91990DE7D55370D79EFCA75F58B183E07F0053183955853AA0513A5E12320C01404D17ADF58D2ED6F80C155F0C"
                "887B4AA17F15AC928DAAA688E96B0C5DA2760FDE6A3FE3D4FA80677DD29FE637B13E8C4FB7DEC287E6DF27DA04545A964DAA49F4624B0EDBDA68897A"
                "6BB5886D6D7A671584772B54054062B34B6F8E8DB8EA6658E092CAA0B993323FB19A5D14DED37CE10503A2C782AFE989D76B0023DD62BDCEC61CE338"
                "25C5C69F4701039F480AEE122B67AA85775FA6CD9000"
            ),

            # 6. READ RECORD SFI=4, record=2
            bytes.fromhex(
                "70078F01069F3201039000"
            ),

            # 7. READ RECORD SFI=4, record=3
            bytes.fromhex(
                "7081FB9081F888A05F6427BE068DF350CC9DBDBD91EBBCF0D1BE8B6464FFA67818D2B82154CF43BFDB82C1500E8936EED9C6C3BEC13B2E07C848B14C"
                "7B9120C2ED99B8904DCDEF89B3AC3D0C6FA1E4BA044FCE39F5DEC94E35A26038B1DD44AF5737A2CCC811D02B1ADFD8EE2D75F6E032EFAE3042E74240"
                "6409E64F804247E7BEC8D3117DBFBAA178EE72B23AF25E72D99BEC2AA78C51F23FEB343E34C854DA2FD19521E6451EC23D1E19D4D4C2D5D91ADD540A"
                "1B3DDAB0A28E1EF190994A01A8C08DD151DDF090AC627B79CAEEC373C99507CED18C211A1DB48F2067C1FD3B37DBE4DAB82E44D036C4D4FCE3853C79"
                "5493C65D1452F0C0E4DEA6C455769000"
            ),

            # 8. FIRST GENERATE AC -> ARQC
            bytes.fromhex(
                "77339F2701809F3602000D9F26084FFA29CF6FD340769F101C3014A04303A40004AE74E26D0A8185D4B460E545E9F534369037000E9000"
            ),
        )

        if len(reference_responses) != len(CAPDUS):
            raise RuntimeError(
                f"reference response count mismatch: CAPDUS={len(CAPDUS)} "
                f"references={len(reference_responses)}"
            )

        try:
            # 1. Registration
            self.send_register()
            if not self.wait_for_register_ack():
                print("ERROR: REGISTER ACK not received.")
                return 2

            # 2. Session negotiation
            self.send_ctrl(f"SESSION_BEGIN {self.session_id}")
            if not self.wait_for_session_ack():
                print("ERROR: session readiness ACK/control not received.")
                return 3

            # 3. Exact eight-CAPDU baseline
            capdus_list = list(CAPDUS)
            if self.cdcvm and len(capdus_list) >= 8:
                gac = bytearray(capdus_list[7])
                if len(gac) >= 5 + 43:
                    gac[5 + 40] = 0x3F
                    gac[5 + 41] = 0x00
                    gac[5 + 42] = 0x00
                    capdus_list[7] = bytes(gac)
                    print("CDCVM: patched 9F34 in first GAC CAPDU → 3F0000")

            for seq, (name, capdu, reference) in enumerate(
                zip(NAMES, tuple(capdus_list), reference_responses), start=1
            ):
                phase = (
                    "PPSE"
                    if seq == 1
                    else "AID_SELECT"
                    if seq == 2
                    else "GPO"
                    if seq == 3
                    else "READ_RECORD"
                    if 4 <= seq <= 7
                    else "FIRST_GAC_ARQC"
                )

                if seq == 3 and self.cdcvm:
                    self.send_ctrl("CDCVM_VERIFIED BIOMETRIC")
                    time.sleep(0.05)

                self.send_apdu(
                    capdu,
                    seq=seq,
                    phase=phase,
                    name=name,
                )
                rapdu = self.wait_for_rapdu(
                    wanted_seq=seq,
                    phase=phase,
                    name=name,
                    reference_response=reference,
                )
                if rapdu is None:
                    print(
                        f"STOP: no RAPDU for CAPDU #{seq} ({name}) "
                        f"within {self.timeout:.1f}s"
                    )
                    self.protocol_state = "ERROR"
                    self.print_trace()
                    self._export()
                    return 4

                print(f"RESULT #{seq}: {name} → SW={sw(rapdu)}")
                print()

                if sw(rapdu) != "9000":
                    print(
                        f"STOP: CAPDU #{seq} ({name}) returned SW={sw(rapdu)}"
                    )
                    self.protocol_state = "ERROR"
                    self.print_trace()
                    self._export()
                    return 5


            # 4. Optional synthetic post-ARQC continuation.
            if self.continue_arqc:
                first_gac = self.trace[-1]
                if first_gac.status != "9000":
                    print("STOP: first GAC did not return SW=9000.")
                    return 5

                first_gac_checkpoint = decode_rapdu_checkpoint(
                    bytes.fromhex(first_gac.apdu_hex)
                )
                cid = first_gac_checkpoint.get("CID_9F27")

                print("POST-ARQC CHECKPOINT")
                print(
                    f"  CID(9F27)={cid or 'NONE'} "
                    f"ATC(9F36)={first_gac_checkpoint.get('ATC_9F36', 'NONE')}"
                )
                print(
                    f"  AC(9F26)={first_gac_checkpoint.get('AC_9F26', 'NONE')}"
                )
                print(
                    f"  IAD(9F10)={first_gac_checkpoint.get('IAD_9F10', 'NONE')}"
                )

                # Only the synthetic lab continuation is sent here. No issuer
                # authentication/ARPC is generated by this emulator.
                seq = 9
                self.send_apdu(
                    EXT_AUTH_APDU,
                    seq=seq,
                    phase="SYNTH_EXT_AUTH",
                    name="EXTERNAL AUTHENTICATE (LAB)",
                )
                rapdu = self.wait_for_rapdu(
                    wanted_seq=seq,
                    phase="SYNTH_EXT_AUTH",
                    name="EXTERNAL AUTHENTICATE (LAB)",
                    reference_response=SYNTHETIC_EXT_AUTH_RAPDU,
                )
                if rapdu is None:
                    print("STOP: synthetic EXT AUTH produced no RAPDU.")
                    return 6

                seq = 10
                self.send_apdu(
                    GAC2_APDU,
                    seq=seq,
                    phase="SECOND_GAC_LAB",
                    name="GENERATE AC #2 (LAB)",
                )
                rapdu = self.wait_for_rapdu(
                    wanted_seq=seq,
                    phase="SECOND_GAC_LAB",
                    name="GENERATE AC #2 (LAB)",
                    reference_response=SYNTHETIC_GAC2_RAPDU,
                )
                if rapdu is None:
                    print("STOP: synthetic second GAC produced no RAPDU.")
                    return 7

                print()
                print("ARQC CONTINUATION: LAB-ONLY COMPLETE")
                print("Issuer authentication / ARPC generation is intentionally")
                print("not performed; use the checkpoints above to compare the")
                print("real POS behavior at the corresponding stage.")

            print("=" * 60)
            self.protocol_state = "COMPLETE"
            print("CAPTURED SEQUENCE COMPLETE")
            if self.continue_arqc:
                print("SYNTHETIC ARQC CONTINUATION COMPLETE")
            print("No retries were issued.")
            self.print_trace()
            self._export()
            return 0

        finally:
            self.close()

    def _export(self) -> None:
        if not self.export_path:
            return
        payload = {
            "harness": "REL8HF EMV Emulator Lab",
            "session_id": self.session_id,
            "client_id": self.client_id,
            "relay": {
                "host": self.relay_addr[0],
                "port": self.relay_addr[1],
            },
            "continue_arqc": self.continue_arqc,
            "protocol_state": self.protocol_state,
            "ctrl_messages": self.ctrl_messages,
            "trace": [asdict(item) for item in self.trace],
            "note": (
                "Synthetic lab diagnostics only. No issuer connection and no "
                "production payment cryptography/ARPC generation."
            ),
        }
        self.export_path.write_text(
            json.dumps(payload, indent=2),
            encoding="utf-8",
        )
        print(f"TRACE JSON: {self.export_path}")


def self_test() -> int:
    """Validate captured APDUs and wire serialization without contacting UDP."""
    expected = (
        "00A404000E325041592E5359532E444446303100",
        "00A4040007A000000004101000",
        "80A800000A8308000000000000000000",
        "00B2011400",
        "00B2012400",
        "00B2022400",
        "00B2032400",
        "80AE80004200000000100000000000"
        "000009780000000000097826081700"
        "B1525BA12200000000000000000000"
        "1F0302084018000000000000000000"
        "000000000000000000000000",
    )

    if not (len(CAPDUS) == len(NAMES) == len(expected) == 8):
        raise AssertionError(
            f"baseline count mismatch: CAPDUS={len(CAPDUS)} "
            f"NAMES={len(NAMES)} expected={len(expected)}"
        )
    if len(CAPDUS[7]) != 72:
        raise AssertionError(
            f"CAPDU #8 GAC length mismatch: expected 72, got {len(CAPDUS[7])}"
        )

    print("REL8HF EMV EMULATOR LAB SELF-TEST")
    print("=" * 60)
    for idx, (actual, want) in enumerate(zip(CAPDUS, expected), start=1):
        actual_hex = hx(actual)
        if actual_hex != want:
            raise AssertionError(
                f"CAPDU #{idx} mismatch:\nactual={actual_hex}\nwant={want}"
            )
        print(f"{idx}. {NAMES[idx - 1]:24s} len={len(actual):2d} {actual_hex}")

    frame = build_frame(
        constants.SID_CAPDU,
        CAPDUS[0],
        epoch=123456,
        seq=7,
    )
    parsed = constants.parse_frame(frame)
    if parsed is None:
        raise AssertionError("representative frame did not parse")
    sid, epoch, seq, payload = parsed
    if (sid, epoch, seq, payload) != (
        constants.SID_CAPDU,
        123456,
        7,
        CAPDUS[0],
    ):
        raise AssertionError("wire frame round-trip mismatch")

    # Validate the known-good first GAC checkpoint locally.
    gac = bytes.fromhex(
        "77339F2701809F3602000D"
        "9F26084FFA29CF6FD34076"
        "9F101C3014A04303A40004AE74E26D0A8185D4B460E545E9F534369037000E"
        "9000"
    )
    checkpoint = decode_rapdu_checkpoint(gac)
    if checkpoint.get("sw") != "9000":
        raise AssertionError("known-good GAC fixture missing SW=9000")
    if checkpoint.get("CID_9F27") != "80":
        raise AssertionError("known-good GAC fixture missing CID=80")
    if checkpoint.get("ATC_9F36") != "000D":
        raise AssertionError("captured GAC fixture missing ATC=000D")

    print()
    print("wire: 11-byte header + raw APDU payload")
    print("exchange correlation: outer Seq")
    print("post-ARQC continuation fixtures: PRESENT")
    print("STATUS: PASS")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="REL8HF lab EMULATOR with captured replay and diagnostic checkpoints"
    )
    parser.add_argument("--relay-host", default="127.0.0.1")
    parser.add_argument("--relay-port", type=int, default=5566)
    parser.add_argument(
        "--client-id",
        default=None,
        help="Explicit EMULATOR identity; defaults to REL8-LAB-EMU-<session>",
    )
    parser.add_argument("--timeout", type=float, default=5.0)
    parser.add_argument("--session-id", default=None)
    parser.add_argument(
        "--continue-arqc",
        action="store_true",
        help="Continue into the synthetic EXT AUTH + second-GAC lab path after ARQC",
    )
    parser.add_argument(
        "--cdcvm",
        action="store_true",
        help="Send CDCVM_VERIFIED BIOMETRIC before GPO and patch 9F34=3F0000 in first GAC",
    )
    parser.add_argument(
        "--export",
        type=Path,
        help="Write the detailed lab trace to JSON",
    )
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    return EmuLab(
        args.relay_host,
        args.relay_port,
        session_id=args.session_id,
        client_id=args.client_id,
        timeout=args.timeout,
        continue_arqc=args.continue_arqc,
        export_path=args.export,
        cdcvm=args.cdcvm,
    ).run()


if __name__ == "__main__":
    raise SystemExit(main())
